import type { Metadata } from "next";
import "./globals.css";
import { ParticlesBackground } from "./ui/ParticlesBackground";
import { NavigationBar } from "./ui/NavigationBar";

export const metadata: Metadata = {
  title: "Kyohei's portfolio.com",
  description: "Kyohei Yonehama's portfolio website generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="ja">
      <body className="min-h-screen flex flex-col">
        <NavigationBar />
        <ParticlesBackground />
        <main className="relative z-10 pt-32 flex-1">{children}</main>
      <footer className="bg-gray-400/30 py-4 mt-4 w-full text-center relative z-50">© 2025 Kyohei Yonehama</footer>
      </body>
    </html>
  );
}
