import type { Metadata } from "next";
import "./globals.css";
import { ParticlesBackground } from "./ui/ParticlesBackground";



export const metadata: Metadata = {
  title: "heigineer_portfolio.com",
  description: "Kyohei Yonehama's portfolio website generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="ja">
      <body>
        <header className="relative z-10 bg-white text-center">portfolio</header>
        <ParticlesBackground />
        <main className="relative z-10">{children}</main>
        <footer className="relative z-10 bg-white text-center">navbar</footer>
      </body>
    </html>
  );
}
