import type { Metadata } from "next";
import "./globals.css";
import { ParticlesBackground } from "./ui/ParticlesBackground";
import { NavigationBar } from "./ui/NavigationBar";
import { ResendForm } from "./ui/ResendForm";



export const metadata: Metadata = {
  title: "heigineer_portfolio.com",
  description: "Kyohei Yonehama's portfolio website generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="ja">
      <body>
        <NavigationBar />
        <ParticlesBackground />
        <main className="relative z-10 pt-32">{children}</main>
      </body>
      
    </html>
  );
}
